### ISSUE TITLE
Which COMMANDs are available?

### ISSUE THREAD

**Issue by kseistrup** [fdavies93/zenkat#4]
```sh
$ zenkat --help
usage: zenkat [OPTIONS] command [command …]
```

But I can't seem to find an easy way to list available COMMANDs. I can peek in `zk.py`, but it would be handy if e.g. `help` were a command, and if COMMANDs were listed (and optionally described).

Cheers.

**Comment by fdavies93** [comment]
Hey - this is on my todo list and will definitely be in the next major release. I might also do a fractional release / update main before then.

**Comment by fdavies93** [comment]
Have implemented by refactoring the structure of the command parsers, update is now on `feature/parsing` branch and will be merged as part of next merge to main and package release.

**Comment by kseistrup** [comment]
Sweet, thanks!
