### ISSUE TITLE
Can't use zenkat

### ISSUE THREAD

**Issue by ghost** [fdavies93/zenkat#5]
Hello, i install zenkat by pip install zenkat, but after install idk, how to start zenkat! zenkat --help doesn't work, zk.py too....

Okay, i find how to start zenkat..
https://docs.python.org/3/tutorial/venv.html#creating-virtual-environments

and next run 1. python -m pip install zenkat
2. zenkat

**Comment by fdavies93** [comment]
I'll check this out in a VM, global installs shouldn't work differently to venv ones.
