### ISSUE TITLE
[Question] Comparison to `zk`?

### ISSUE THREAD

**Issue by JetpackJackson** [fdavies93/zenkat#6]
Hi, I came across your tool but I'm trying to figure out the differences between it and [zk](https://github.com/mickael-menu/zk) which is what I'm currently using, even though I read through the readme. Also, does zenkat work with .tex files as well as markdown? I couldn't find mention of it in the readme but I might've missed it. Thanks in advance!

**Comment by fdavies93** [comment]
Hi, I think generally the difference is that zk is more focused on providing utilities for manipulating notes, while zenkat is more focused on querying existing notes. However I do have a few utilities I want to add to the project, notably a task manager.

Currently zenkat only supports MD files but open to supporting more formats in the future.

**Comment by JetpackJackson** [comment]
Alright, thank you! It would be neat to see .tex files added, since my notes are a mix of tex and md files lol.
